/**
 * Regression gate for the ACFTA extract (db/seed/data/fta-acfta.ndjson).
 *
 * ND 118/2022/NĐ-CP has a per-line column "Nước không được hưởng ưu đãi"
 * (Điều 3 khoản 5). Re-extracting the biểu to capture it must not move a single
 * rate: every line is compared against the pre-fix extract at BASELINE, and the
 * only difference allowed is the new exclusion fields. No database needed.
 */
import { execFileSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

interface SubLine { hs10: string; hs_dotted: string; desc: string; rates: string[]; excluded: string[] }
interface Row { hs: string; hs_dotted: string; desc: string; rates: string[]; excluded?: string[]; excluded_sublines?: SubLine[] }

const ROOT = join(__dirname, '..', '..');
const BASELINE = '9e3431d'; // last commit carrying the extract without the exclusion column
const ND118_CODES = ['BN', 'KH', 'ID', 'LA', 'MY', 'MM', 'PH', 'SG', 'TH', 'CN']; // ND 118/2022 Điều 4 khoản 2
const parse = (text: string): Row[] => text.trim().split('\n').map((l) => JSON.parse(l) as Row);
const data = (f: string) => readFileSync(join(__dirname, 'data', f), 'utf8');

const rows = parse(data('fta-acfta.ndjson'));
const git = (...args: string[]) =>
  execFileSync('git', args, { cwd: ROOT, encoding: 'utf8', maxBuffer: 64 * 1024 * 1024, stdio: ['ignore', 'pipe', 'ignore'] });
let inGitRepo = true;
try {
  git('rev-parse', '--is-inside-work-tree');
} catch {
  inGitRepo = false; // e.g. a container build without .git — the invariants below still run
}

const validCodes = (codes: string[] | undefined) =>
  !!codes && codes.length > 0 && codes.every((c) => ND118_CODES.includes(c)) &&
  codes.join() === [...new Set(codes)].sort().join();

describe('ACFTA extract', () => {
  // Skipped only outside a git work tree. Inside one, a missing baseline (shallow clone,
  // rewritten history) fails here: this is the one test that proves no rate moved.
  (inGitRepo ? test : test.skip)('has 0 differences in hs/hs_dotted/desc/rates against the pre-fix extract', () => {
    const base = parse(git('show', `${BASELINE}:db/seed/data/fta-acfta.ndjson`));
    expect(rows.length).toBe(base.length);
    const diffs = rows
      .map((r, i) => ({ r, b: base[i]! }))
      .filter(({ r, b }) => JSON.stringify([r.hs, r.hs_dotted, r.desc, r.rates]) !== JSON.stringify([b.hs, b.hs_dotted, b.desc, b.rates]))
      .map(({ r, b }) => `${b.hs_dotted} ${JSON.stringify(b.rates)} -> ${r.hs_dotted} ${JSON.stringify(r.rates)}`);
    expect(diffs).toEqual([]);
  });

  test('carries only the known fields, with valid sorted ND 118 codes', () => {
    const bad = rows.filter(
      (r) =>
        Object.keys(r).some((k) => !['hs', 'hs_dotted', 'desc', 'rates', 'excluded', 'excluded_sublines'].includes(k)) ||
        (r.excluded !== undefined && !validCodes(r.excluded)) ||
        (r.excluded_sublines ?? []).some((s) => !s.hs_dotted.startsWith(r.hs_dotted + '.') || s.hs10 !== s.hs_dotted.replace(/\./g, '') || !validCodes(s.excluded)),
    );
    expect(bad.map((r) => r.hs_dotted)).toEqual([]);
  });

  test('matches the decree on known lines and the measured counts', () => {
    const by = new Map(rows.map((r) => [r.hs_dotted, r]));
    expect(by.get('0901.11.20')).toEqual({ hs: '09011120', hs_dotted: '0901.11.20', desc: '- - - Arabica', rates: ['0'], excluded: ['CN', 'MM', 'TH'] });
    // A 10-digit sub-line exclusion stays on the sub-line, never on the whole HS8 line.
    const parent = by.get('1211.60.00')!;
    expect(parent.excluded).toBeUndefined();
    expect(parent.excluded_sublines?.map((s) => [s.hs_dotted, s.excluded])).toEqual([['1211.60.00.10', ['MM', 'TH']]]);

    // Every 10-digit sub-line of 4011.80.31 excludes ID (the residual .90 "Loại khác" too),
    // so the whole 8-digit line is excluded for ID; MY stays a sub-line exclusion.
    expect(by.get('4011.80.31')?.excluded).toEqual(['ID']);
    expect(by.get('4011.80.31')?.excluded_sublines?.map((s) => s.excluded)).toEqual([['ID', 'MY'], ['ID']]);

    expect(rows.filter((r) => r.excluded).length).toBe(3154);
    expect(rows.reduce((n, r) => n + (r.excluded_sublines?.length ?? 0), 0)).toBe(34);
    expect(rows.filter((r) => r.excluded?.includes('CN')).length).toBe(509);
  });

  // Guards the committed seed inputs (not regenerated by this fix), not the parser:
  // research/fta-loader/test_parse_fta.py covers the parser.
  test('AANZFTA, ATIGA and EVFTA have no per-country column (only "*")', () => {
    for (const f of ['fta-aanzfta.ndjson', 'fta-atiga.ndjson', 'fta-evfta.ndjson']) {
      expect(data(f).includes('"excluded')).toBe(false);
    }
  });
});
